function SymbolCrossStreet() {
  return (
    <svg width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
      <title>icon/ic_cross_street</title>
      <desc>Created with Sketch.</desc>
      <defs />
      <g
        id="Symbols"
        stroke="none"
        strokeWidth="1"
        fill="none"
        fillRule="evenodd"
      >
        <g id="icon/ic_cross_street">
          <g id="ic_cross_street">
            <rect id="boundry" x="0" y="0" width="24" height="24" />
            <rect
              id="Rectangle-42"
              fill="#333333"
              x="9"
              y="3"
              width="2"
              height="5"
              rx="0.5"
            />
            <rect
              id="Rectangle-42"
              fill="#333333"
              x="9"
              y="16"
              width="2"
              height="5"
              rx="0.5"
            />
            <rect
              id="Rectangle-42"
              fill="#333333"
              x="14"
              y="3"
              width="2"
              height="3"
              rx="0.5"
            />
            <rect
              id="Rectangle-42"
              fill="#333333"
              x="14"
              y="8"
              width="2"
              height="3"
              rx="0.5"
            />
            <rect
              id="Rectangle-42"
              fill="#333333"
              x="14"
              y="13"
              width="2"
              height="3"
              rx="0.5"
            />
            <rect
              id="Rectangle-42"
              fill="#333333"
              x="14"
              y="18"
              width="2"
              height="3"
              rx="0.5"
            />
            <rect
              id="Rectangle-42"
              fill="#333333"
              x="19"
              y="3"
              width="2"
              height="18"
              rx="0.5"
            />
            <rect
              id="Rectangle-57"
              fill="#333333"
              x="3"
              y="6"
              width="7"
              height="2"
              rx="0.5"
            />
            <rect
              id="Rectangle-57"
              fill="#333333"
              x="8"
              y="11"
              width="3"
              height="2"
              rx="0.5"
            />
            <rect
              id="Rectangle-57"
              fill="#333333"
              x="3"
              y="11"
              width="3"
              height="2"
              rx="0.5"
            />
            <rect
              id="Rectangle-57"
              fill="#333333"
              x="3"
              y="16"
              width="7"
              height="2"
              rx="0.5"
            />
          </g>
        </g>
      </g>
    </svg>
  );
}

export default SymbolCrossStreet;
