const faker = require('faker');

var data = [{"full_name":"Westbrook Hodge"},
{"full_name":"Henka Silman"},
{"full_name":"Skelly Trebilcock"},
{"full_name":"Deeyn Josiah"},
{"full_name":"Lizabeth Everitt"},
{"full_name":"Mollie Shickle"},
{"full_name":"Raddie Sizland"},
{"full_name":"Anastasia Labone"},
{"full_name":"Callean Balazs"},
{"full_name":"Jud Pladen"},
{"full_name":"Shari Gossage"},
{"full_name":"Bud Goss"},
{"full_name":"Alexandros Hallock"},
{"full_name":"Damita Lyver"},
{"full_name":"Zach Brunesco"},
{"full_name":"Noe Creeboe"},
{"full_name":"Hedwig Orgen"},
{"full_name":"Jenda Chaves"},
{"full_name":"Caryl Trusty"},
{"full_name":"Marcel Lowey"},
{"full_name":"Zackariah Wallentin"},
{"full_name":"Berty Chartman"},
{"full_name":"Ephraim Wildor"},
{"full_name":"Jamill Stacey"},
{"full_name":"Sauncho Ledner"},
{"full_name":"Melissa Kless"},
{"full_name":"Selle Kays"},
{"full_name":"Jeana Cortin"},
{"full_name":"Bridie Spittles"},
{"full_name":"Datha O'Cahsedy"},
{"full_name":"Ronnica Giddins"},
{"full_name":"Zelma Keightley"},
{"full_name":"Waylon Magor"},
{"full_name":"Wandis Townson"},
{"full_name":"Paquito Surmeyers"},
{"full_name":"Addie Manuelli"},
{"full_name":"Andrea Wield"},
{"full_name":"Bucky Margerrison"},
{"full_name":"Randell Marsham"},
{"full_name":"Ashien McCulloch"},
{"full_name":"Adeline O'Growgane"},
{"full_name":"Ingunna Noquet"},
{"full_name":"Iseabal Ineson"},
{"full_name":"Nalani MacFaell"},
{"full_name":"Ross Roelofsen"},
{"full_name":"Nerty Kezar"},
{"full_name":"Olive Wetherhead"},
{"full_name":"Fannie Sheirlaw"},
{"full_name":"Horten Pinches"},
{"full_name":"Dorita Sapsed"},
{"full_name":"Fleurette Currer"},
{"full_name":"Dionis Staneland"},
{"full_name":"Dag Losano"},
{"full_name":"Cairistiona McGaughie"},
{"full_name":"Bordy Cato"},
{"full_name":"Eadith Fumagalli"},
{"full_name":"Rustin Tranfield"},
{"full_name":"Burton Felten"},
{"full_name":"Lana Heighton"},
{"full_name":"Susanna Gooderridge"},
{"full_name":"Molly Diviny"},
{"full_name":"Inesita Toupe"},
{"full_name":"Wyn Harback"},
{"full_name":"Larina Ventom"},
{"full_name":"Hakeem Fullom"},
{"full_name":"Gussi Press"},
{"full_name":"Keenan Glyne"},
{"full_name":"Marja Cabrer"},
{"full_name":"Delores Sawfoot"},
{"full_name":"Hannie Bloxland"},
{"full_name":"Carney Phil"},
{"full_name":"Mendie O' Gara"},
{"full_name":"Larine Helversen"},
{"full_name":"Chuck Sinnett"},
{"full_name":"Stavro Feacham"},
{"full_name":"Brooks Powe"},
{"full_name":"Nolie Saggs"},
{"full_name":"Lisbeth Syres"},
{"full_name":"Bale Kiljan"},
{"full_name":"Harper Snepp"},
{"full_name":"Merl Lucken"},
{"full_name":"Betsey Sandifer"},
{"full_name":"Hillary Barthrup"},
{"full_name":"Ewell Wodham"},
{"full_name":"Nike Walrond"},
{"full_name":"Ichabod Filippone"},
{"full_name":"Leandra Wesgate"},
{"full_name":"Brett Remnant"},
{"full_name":"Leslie Bewlay"},
{"full_name":"Vassily Cartmer"},
{"full_name":"Selle Lecordier"},
{"full_name":"Randell Buske"},
{"full_name":"Marje Lorrie"},
{"full_name":"Emilie Sparrowhawk"},
{"full_name":"Morgana Catchpole"},
{"full_name":"Christoper Warne"},
{"full_name":"Paige Bernolet"},
{"full_name":"Harriot Basill"},
{"full_name":"Alia Terrington"},
{"full_name":"Anallise Rubinowitch"},
{"full_name":"Bryan Plunkett"},
{"full_name":"Marylee Gatrell"},
{"full_name":"Christopher Groger"},
{"full_name":"Hercule Houlden"},
{"full_name":"Brittaney Inkle"},
{"full_name":"Herrick Winks"},
{"full_name":"Carver Perryn"},
{"full_name":"Nicolle Rowe"},
{"full_name":"Zilvia Bowmaker"},
{"full_name":"Gloriane Bigley"},
{"full_name":"Bunny Smallpeace"},
{"full_name":"Marcela Cashen"},
{"full_name":"Ichabod Etherson"},
{"full_name":"Rees Storr"},
{"full_name":"Afton Lockhart"},
{"full_name":"Naomi Kiledal"},
{"full_name":"Marve Le Pruvost"},
{"full_name":"Fae MacCrann"},
{"full_name":"Cordy Isaksen"},
{"full_name":"Lyn Caltun"},
{"full_name":"Neal Stoker"},
{"full_name":"Lotte Cooper"},
{"full_name":"Janette Turpin"},
{"full_name":"Parker O'Riordan"},
{"full_name":"Batsheva Glidder"},
{"full_name":"Sybilla Matusov"},
{"full_name":"Kessiah Pratt"},
{"full_name":"Somerset Beevis"},
{"full_name":"Ingram Simonetti"},
{"full_name":"Kakalina Fairchild"},
{"full_name":"Carmella Inger"},
{"full_name":"Ludovika Sedwick"},
{"full_name":"Carole Haysham"},
{"full_name":"Alfi Hazeley"},
{"full_name":"Pinchas Longfellow"},
{"full_name":"Elliott Bedminster"},
{"full_name":"Alic Jinda"},
{"full_name":"Brigit Sponder"},
{"full_name":"Randy MacDonagh"},
{"full_name":"Erinna Mouat"},
{"full_name":"Jody Martynov"},
{"full_name":"Georas Peevor"},
{"full_name":"Harlene O'Keevan"},
{"full_name":"Jackquelin Liddyard"},
{"full_name":"Steffie Taylo"},
{"full_name":"Duane Hanna"},
{"full_name":"Elicia Rohlfing"},
{"full_name":"Angelita Grindrod"},
{"full_name":"Emelen Goane"},
{"full_name":"Gianna McGrail"},
{"full_name":"Marcile Jenk"},
{"full_name":"Lucine Studd"},
{"full_name":"Ronnica Traill"},
{"full_name":"Julius Jedryka"},
{"full_name":"Rey Brennan"},
{"full_name":"Seline Castane"},
{"full_name":"Paxon Enderle"},
{"full_name":"Karim Wyche"},
{"full_name":"Guthrey Denizet"},
{"full_name":"Roy Oneile"},
{"full_name":"Iain Greim"},
{"full_name":"Juan Crisp"},
{"full_name":"Consalve Nisbet"},
{"full_name":"Zandra MacTrustrie"},
{"full_name":"Hermione Maria"},
{"full_name":"Hasheem Balloch"},
{"full_name":"Evered Kenton"},
{"full_name":"Brande Bemment"},
{"full_name":"Shir Birdseye"},
{"full_name":"Marieann Penrith"},
{"full_name":"Durward Tilio"},
{"full_name":"Ram Benet"},
{"full_name":"Ulrika Halsted"},
{"full_name":"Wallace Oake"},
{"full_name":"Dick Vannoort"},
{"full_name":"Silvano Sidlow"},
{"full_name":"Ricki Gerold"},
{"full_name":"Elvira Fanning"},
{"full_name":"Dannie Tutt"},
{"full_name":"Augustine Birdwhistle"},
{"full_name":"Carolee Pordal"},
{"full_name":"Astrid Moverley"},
{"full_name":"Barron Henden"},
{"full_name":"Aridatha Mogie"},
{"full_name":"Noak Armitage"},
{"full_name":"Juliet Pentlow"},
{"full_name":"Nevsa Kille"},
{"full_name":"Kimball Worrell"},
{"full_name":"Ulrike Dundridge"},
{"full_name":"Ephrem Blakeman"},
{"full_name":"Gerek Richens"},
{"full_name":"Edmund Jaspar"},
{"full_name":"Jessica Tarbett"},
{"full_name":"Sara Gosz"},
{"full_name":"Priscella Keers"},
{"full_name":"Alika Grayshan"},
{"full_name":"Brade Hallward"},
{"full_name":"Kathe Demschke"},
{"full_name":"Massimiliano Lindelof"},
{"full_name":"Raviv Nesby"}]

var generateData = function(object) {
  var newArray = [];
  for (var i = 0; i < object.length; i++) {
    newArray.push(object[i].full_name)
  }
  return newArray;
}

// var generateNames = () => {
//   var result = []; 
//    var count = 0; 
//    for (var i=count; i < 10; i++){
//     count++; 
//     while (i < count){
//       result.push(faker.name.findName()) 
//     }
//    }
//    console.log(result.length)
//   return result; 
  
// }

module.exports = generateData(data);